# yaml-language-server: $schema=https://soymadip.github.io/portosaur/user/config/schema.json
#
# Portosaur Project Configuration
# Check full Config Docs: https://soymadip.is-a.dev/portosaur/guide/config
#

# User variables for use in your values as {{vars.key}}
vars:
  twitter: "@{{user_name}}"
  github: "{{user_name}}"
  linkedin: "{{user_name}}"

# Site Metadata, SEO, Parser behavior
site:
  url: "auto"
  base_url: "auto"

# UI, Navigation Behavior
theme:
  navigation:
    collapsable_sidebar: true

# Page Content & Sections
home_page:
  hero:
    title: "{{full_name}}"
    profession: "Your Profession"
    desc: "Short description about you, your passion, your goals etc."
    profile_pic: "img/icon.png"

    social:
      - name: "LinkedIn"
        url: "https://www.linked.com/in/{{user_name}}"

      - name: "GitHub"
        icon: "githubalt" # TODO: needs documentation
        url: "https://github.com/{{user_name}}"

      - name: "Telegram"
        url: "https://t.me/{{user_name}}"

  about:
    enable: true
    image: "{{home_page.hero.profile_pic}}"
    bio:
      - "I'm a {{home_page.hero.profession}} who loves turning ideas into reality."
      - "With a background in computer science and a passion for design, I bridge the gap between aesthetics and functionality."
      - "Also I am interested in Your interest1, interest2 etc etc......"
    skills:
      - "skill 1"
      - "skill 2"
      - "skill 3"
    resume: "{{porto_static}}/sample-resume.pdf"

  project_shelf:
    enable: true
    projects:
      - title: "Your Awesome Project"
        icon: null
        state: "active" # options: active, completed, maintenance, paused, archived, planned
        desc: "A brief description of what this project does and the tech used."
        tags: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7"]
        website: "https://example.com"
        repo: "https://github.com/yourname/project1"

      - title: "Your Awesome Project 2"
        icon: "img/project-blank.png"
        bg: "#5c8f2d"
        tags: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7"]
        featured: true
        state: "completed"
        desc: "A brief description of what this project does and the tech used."
        website: "https://example.com"
        repo: "https://github.com/yourname/project2"
        demo: "https://example.com/demo"

      - title: "Your Awesome Project 3"
        icon: "https://github.com/soymadip/KireiSakura-Kit/blob/main/Assets/icon.png?raw=true"
        bg: "#aa47be"
        state: "completed"
        desc: "A brief description of what this project does and the tech used."
        website: "https://example.com"
        repo: "https://github.com/yourname/project2"
        demo: "https://example.com/demo"

  experience:
    enable: false
    list:
      - company: "Tech Solutions Inc."
        role: "Senior Developer"
        duration: "2022 - Present"
        desc: "Leading the frontend team in building a high-performance dashboard."

  # Reach me out section
  social:
    enable: true
    links:
      - name: "Email"
        desc: "Send me an email"
        url: "mailto:yourname@example.com"

      - name: "LinkedIn"
        desc: "Connect on LinkedIn"
        url: "https://linkedin.com/in/{{user_name}}"

      - name: "Telegram"
        desc: "Reach me on Telegram"
        url: "https://t.me/{{user_name}}"

      - name: "Discord"
        desc: "Become my friend"
        url: "https://discord.com/users/yourid"

      - name: "Twitter"
        desc: "Find me on Twitter"
        url: "https://twitter.com/{{user_name}}"

      - name: "GitLab"
        desc: "View my GitLab profile"
        url: "https://gitlab.com/{{user_name}}"

      - name: "Anilist"
        desc: "If you are otaku, check out!"
        url: "https://anilist.co/user/{{user_name}}"

tasks:
  enable: true
  list:
    - title: "Build the future"
      status: "done"
      desc: "Implementing the core framework."
