const fs = require("fs");
const path = require("path");

const projectDir = process.cwd();
const configPath1 = path.resolve(projectDir, "config.yml");
const configPath2 = path.resolve(projectDir, "config.yaml");
const configPath = fs.existsSync(configPath1) ? configPath1 : configPath2;

let isDocsMode = false;
if (fs.existsSync(configPath)) {
  try {
    const content = fs.readFileSync(configPath, "utf8");
    if (/^\s*docs_home\s*:/m.test(content)) {
      isDocsMode = true;
    }
  } catch (e) {}
}

let rootDocId = null;
try {
  const docsDir = path.resolve(projectDir, "docs");
  if (fs.existsSync(docsDir)) {
    const files = fs.readdirSync(docsDir);
    for (const file of files) {
      if (/^index\.(md|mdx)$/i.test(file)) {
        rootDocId = "index";
        break;
      }
      if (/^readme\.(md|mdx)$/i.test(file)) {
        rootDocId = "README";
        break;
      }
    }
  }
} catch (e) {
  console.log("ERROR in sidebar.jsx:", e);
}

const docsCategoryLink = rootDocId
  ? { type: "doc", id: rootDocId }
  : { type: "generated-index", slug: "/" };

const sidebar = {
  notes: isDocsMode
    ? [
        {
          type: "category",
          label: "Docs",
          link: docsCategoryLink,
          items: [
            {
              type: "autogenerated",
              dirName: ".",
            },
          ],
        },
      ]
    : [
        {
          type: "category",
          label: "Notes",
          link: { type: "generated-index", slug: "/" },
          items: [{ type: "autogenerated", dirName: "." }],
        },
      ],
};

module.exports = sidebar;
