import fs from "fs";
import path from "path";
import { spawn } from "child_process";
import { createRequire } from "module";

/**
 * Generates a static Docusaurus config file by evaluating the Portosaur config
 * at CLI time and serializing the result. This avoids importing @portosaur/core
 * inside Docusaurus' own build/serve runtime.
 *
 * @param {string} UserRoot - The user's project directory.
 * @param {Object} portoPaths - Paths to Portosaur assets and theme.
 * @param {Object} [context={}] - Additional context for config generation.
 * @returns {string} The path to the generated config file.
 */
export function writeConfigShim(UserRoot, portoPaths, context = {}) {
  const dotDir = path.join(UserRoot, ".docusaurus", "portosaur");

  if (!fs.existsSync(dotDir)) {
    fs.mkdirSync(dotDir, { recursive: true });
  }

  // Serialize the config as a dynamic export so Docusaurus can evaluate it at runtime,
  // preserving any functions, regexes, and plugin module imports.
  const shimContent = `// Auto-generated by portosaur — do not edit
import { loadUserConfig, buildDocuConfig } from "@portosaur/core";

export default async function createConfig() {
  const UserRoot = ${JSON.stringify(UserRoot)};
  const rawConf = loadUserConfig(UserRoot);
  return buildDocuConfig(rawConf, UserRoot, {
    portoPaths: ${JSON.stringify(portoPaths)},
    portoRoot: ${JSON.stringify(path.resolve(portoPaths.root))},
    ...${JSON.stringify(context)}
  });
}
`;

  const shimPath = path.join(dotDir, "docusaurus.config.js");
  fs.writeFileSync(shimPath, shimContent);

  return shimPath;
}

/**
 * Validate that the current directory is a Portosaur project.
 * @param {string} UserRoot - The directory to validate.
 * @throws {Error} If config.yml is missing.
 */
export function validateProject(UserRoot) {
  const configPath = ["config.yaml", "config.yml"].find((file) =>
    fs.existsSync(path.join(UserRoot, file)),
  );

  if (!configPath) {
    throw new Error(
      "config.yml/config.yaml not found. Are you in a Portosaur project directory?",
    );
  }
}

/**
 * Ensure essential user content directories exist.
 * @param {string} UserRoot - The project root directory.
 */
export function ensureContentDirs(UserRoot) {
  for (const dir of ["notes", "blog", "static"]) {
    if (!fs.existsSync(path.join(UserRoot, dir))) {
      fs.mkdirSync(path.join(UserRoot, dir), { recursive: true });
    }
  }
}

/**
 * Print deployment tips defined in registry.yml
 * @param {Object} hostingPlatforms - Hosting platforms registry.
 * @param {string} hostingPlatformKey - The selected platform key.
 * @param {Object} logger - The Portosaur logger instance.
 * @param {Object} [vars={}] - Variables for replacement in tips.
 */
export function printWorkflowTips(
  hostingPlatforms,
  hostingPlatformKey,
  logger,
  vars = {},
) {
  const config = hostingPlatforms[hostingPlatformKey];
  if (config && config.post_setup_tips) {
    for (let tip of config.post_setup_tips) {
      if (vars.projectName)
        tip = tip.replace(/\{\{projectName\}\}/g, vars.projectName);
      if (vars.userName) tip = tip.replace(/\{\{user\}\}/g, vars.userName);
      logger.tip(tip);
    }
  }
}

/**
 * Warn the user if their project name does not match the expected platform repository pattern.
 * @param {Object} hostingPlatforms - Hosting platforms registry.
 * @param {string} hostingPlatformKey - The selected platform key.
 * @param {string} projectName - Current project name.
 * @param {string} userName - VCS username.
 * @param {Object} logger - The Portosaur logger instance.
 * @param {string} [heading] - Warning heading.
 */
export function warnIfRepoNameMismatch(
  hostingPlatforms,
  hostingPlatformKey,
  projectName,
  userName,
  logger,
  heading = "Project Name Mismatch",
) {
  const config = hostingPlatforms[hostingPlatformKey];
  if (!config || !config.repo || !config.repo.ideal_name) return;

  const expectedRepo = config.repo.ideal_name
    .replace("{{user}}", userName || "yourusername")
    .replace("{{domain}}", config.domain || "");

  if (projectName === expectedRepo || !config.repo.mismatch_msg) return;

  const projectNameForMsg = projectName || "(custom name)";

  const customMsg = config.repo.mismatch_msg
    .replace(/\{\{user\}\}/g, userName || "yourusername")
    .replace(/\{\{projectName\}\}/g, projectNameForMsg)
    .replace(/\{\{domain\}\}/g, config.domain || "")
    .replace(/\{\{idealName\}\}/g, expectedRepo);

  logger.warn(`[${heading}] ${customMsg}`);
}

/**
 * Executes a Docusaurus command.
 *
 * @param {string} command - Docusaurus command to run (e.g., 'start', 'build').
 * @param {string} UserRoot - The project directory.
 * @param {string} configPath - Path to the docusaurus.config.js shim.
 * @param {string[]} [extraArgs=[]] - Additional CLI arguments.
 * @returns {Promise<void>}
 */
export async function runDocusaurus(
  command,
  UserRoot,
  configPath,
  extraArgs = [],
) {
  const require = createRequire(import.meta.url);
  let docusaurusBin;

  try {
    docusaurusBin = require.resolve("@docusaurus/core/bin/docusaurus.mjs", {
      paths: [UserRoot],
    });
  } catch {
    docusaurusBin = path.join(
      UserRoot,
      "node_modules",
      "@docusaurus",
      "core",
      "bin",
      "docusaurus.mjs",
    );
  }

  const args = [docusaurusBin, command, UserRoot];

  if (configPath) {
    args.push("--config", configPath);
  }

  args.push(...extraArgs);

  // Use bun when available for faster builds, fall back to node.
  const runtime = typeof Bun !== "undefined" ? "bun" : "node";

  // Skip actual execution in test mode
  if (process.env.PORTO_TEST_MODE === "true") {
    console.log(
      `[TEST_MODE] Would run docusaurus ${command} in ${UserRoot} using ${runtime}`,
    );
    return Promise.resolve();
  }

  const childEnv = { ...process.env, FORCE_COLOR: "true" };

  if (command === "build") {
    childEnv.CI = "true";
  }

  const child = spawn(runtime, args, {
    stdio: "inherit",
    cwd: UserRoot,
    env: childEnv,
  });

  return new Promise((resolve, reject) => {
    child.on("error", reject);

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Docusaurus exited with code ${code}`));
      }
    });
  });
}
